parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Pixiekat\MolecularTumorBoardBundle\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
  Pixiekat\MolecularTumorBoardBundle\Controller\DashboardController: ~