parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Pixiekat\MolecularTumorBoard\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  Pixiekat\MolecularTumorBoard\Form\:
    resource: '../src/Form/*'
    autowire: true
    autoconfigure: true

  Pixiekat\MolecularTumorBoard\Services\:
    resource: '../src/Services/*'
    public: true
    tags: ['controller.service_arguments']

  Pixiekat\MolecularTumorBoard\Services\TranslationLoader:
    arguments: ['../translations']
